name: Translate Readme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Adding License
        uses: groloboy/cloudProject@v1
        with:
          LANG: es
          # ISO Langusge Code.
          # Supported Languages below
